theme: osuny
_merge: deep
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: '/assets/images/logo.svg'
    footer: '/assets/images/logo.svg'
  home:
    head:
      title: site
  organizations:
    single:
      backlinks: true
  persons:
    single:
      backlinks: true
  events:
    index:
      highlight_exhibitions:
        future:
          layout: agenda
          options:
            dates: true
            categories: true
            image: true
            status: false
            subtitle: true
            summary: false